# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  _<h3>Thanks for opening your first issue here ğŸ™‹ğŸ•µï¸</h3>_

  <img src="https://media.giphy.com/media/10UeedrT5MIfPG/giphy.gif" width="40%">
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  _<h3>Thanks for opening this pull request ğŸ’œğŸ’›ğŸ’šğŸ’™</h3>_
  
  <img src="https://c.tenor.com/kRFqZKvBuPIAAAAi/raf-rafs.gif" width="40%">
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  _<h3>Congrats on merging your first pull request ğŸ†ğŸ‰ğŸŒˆ</h3>_
  
  <img src="https://media.giphy.com/media/OotF5vayuyWEm7iQ4A/giphy.gif" width="40%">
# It is recommended to include as many gifs and emojis as possible!
